# The URL the site will be built for
base_url = "https://blog.dbarnett.nz"

compile_sass = true

# When set to "true", a search index is built from the pages and section
# content for `default_language`.
build_search_index = true

title = "Title can be filled in later"
default_language = "en"

theme = "DeepThunk"

generate_feeds = true
feed_filenames = [ "rss.xml" ]

taxonomies = [
	{ name = "categories", feed = true, paginate_by = 10 },
	{ name = "tags", feed = true, paginate_by = 10 },
]

[markdown]
highlight_code = true
highlight_theme = "demain"

external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

[link_checker]
# Skip link checking for external URLs that start with these prefixes
skip_prefixes = [
    "http://twitter.com/",
    "https://twitter.com/",
]

# Skip anchor checking for external URLs that start with these prefixes
skip_anchor_prefixes = [
]

# Various slugification strategies, see below for details
# Defaults to everything being a slug
[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = false
# Whether to include the rendered content of the page/section in the index
include_content = true

[translations]

[extra]
navbar_items = [
	{ url = "$BASE_URL/", name = "Home" },
	{ url = "$BASE_URL/posts", name = "Posts" },
	{ url = "$BASE_URL/tags", name = "Tags" },
	{ url = "$BASE_URL/categories", name = "Categories" },
]
# Put all your custom variables here

[extra.favicon]
favicon_16x16 = "/icons/favicon-16x16.png"
favicon_32x32 = "/icons/favicon-32x32.png"
apple_touch_icon = "/icons/apple-touch-icon.png"
safari_pinned_tab = "/icons/safari-pinned-tab.svg"
webmanifest = "/icons/site.webmanifest"

# Author details
[extra.author]
name = "David"
avatar = "/images/avatar.png"

# Social link setup
[extra.social]
github = "dbanetto"
